import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Roles',
      collapsed: false,
      items: [
        'roles/ah-counter',
        'roles/ballot-counter',
        'roles/evaluator',
        'roles/general-evaluator',
        'roles/grammarian',
        'roles/speaker',
        'roles/table-topics-master',
        'roles/timer',
        'roles/toastmaster',
      ],
    },
    {
      type: 'category',
      label: 'Officers',
      collapsed: false,
      items: [
        'officer/president',
        'officer/saa',
        'officer/secretary',
        'officer/treasurer',
        'officer/vpe',
        'officer/vpm',
        'officer/vppr',
      ],
    },
    { type: 'autogenerated', dirName: 'others' },
  ],
};

export default sidebars;
