name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GIT_USER: ${{ github.actor }}
      GIT_TOKEN: ${{ secrets.HDTM_GITHUB_TOKEN }}
      PROJECT_NAME: ${{ github.event.repository.name }}
      REPO_OWNER: ${{ github.event.repository.owner.login }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'

      - name: Print environment variables
        run: |
          echo "GIT_USER=${{ env.GIT_USER }}"
          echo "PROJECT_NAME=${{ env.PROJECT_NAME }}"
          echo "REPO_OWNER=${{ env.REPO_OWNER }}"

      - name: Install dependencies
        run: npm install

      - name: Run deploy script
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://${{ env.REPO_OWNER }}:${{ secrets.HDTM_GITHUB_TOKEN }}@github.com/${{ env.REPO_OWNER }}/${{ env.PROJECT_NAME }}.git

          npm run deploy
